### ISSUE TITLE
Unable to revoke did document

### ISSUE THREAD

**Issue by asepkc** [Open-Attestation/ocsp-responder#11]
curl --request POST \
  --url https://ocsp-sandbox.openattestation.com/ \
  --header 'Content-Type: application/json' \
  --data '{
  "documentHash": "0x13e53a698cd616a4df6781d6e61ce851c06ffe27db11b4bbcc7e7b4f76935a53",
  "reasonCode": 3
}'

I used this curl to test, may I know what the issue ?
I use ocsp host: https://ocsp-sandbox.openattestation.com

**Comment by zixiang2018** [comment]
Hi @asepkc, do try to run the repo locally and follow our [readme](https://github.com/Open-Attestation/ocsp-responder/blob/main/README.md) for your own demo purposes. 

The ocsp-sandbox URL (https://ocsp-sandbox.openattestation.com) that you have tried is only for reference purposes. It only allows for `GET` requests and does not allow for `POST` (revocation) or `DELETE` (undo revocation) request. It would be best that you deploy your own OCSP responder or test out the endpoints locally first.

After running the repo locally, you can replace the URL with your localhost URL to test the revocation endpoints.

Hope this helps!

**Comment by asepkc** [comment]
thanks a lot, 
so actually we can make our own ocsp responder even though we don't use the code on the github ocsp, right? as long as the endpoint, payload and response are adjusted to the sample from Github, right?
